jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - run:
          name: test.sh
          command: uname -a
      - run:
          name: test.sh
          command: test.sh
